from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def jq_example1(request):
    return HttpResponse("<p>New paragraph generated by views.jq_example1</p>")
    
def jq_example2(request):
    if request.GET:
        swaptext = request.GET['swaptext']
        if swaptext == "":
            swaptext = "(empty)"
    else:
        swaptext = "No text submitted"
    
    return HttpResponse("<input id='ts2_text_field' type='text' value='" + swaptext + "' name='newtextq'><button type='button' onclick='ajaxsubmit()' class='btn'> Submit </button>")
    
def jq_example2_submit(request):
    if request.GET:
        swaptext = request.GET['swaptext']
        return HttpResponse("<span id='ts2''>" + swaptext + "</span>" +
                            "<button id ='ts2-swap-btn' swap-area-id='test-area2'" +
                            " class='btn' type='button' onclick='ts2swaptext()'>Swap Text</button>")
    else:
        return HttpResponse("<p>'swaptext' not defined")
        
    