from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

def jq_example1(request):
    return HttpResponse("<p>New paragraph generated by views.jq_example1</p>")
    
def jq_example2_edit_text(request):
    if request.GET:
        origtext = request.GET['origtext']
        if origtext == "":
            origtext = "(empty)"
    else:
        origtext = "No text submitted"
    
    return HttpResponse("<input id='ts2_text_field' type='text' value='" + origtext + "' name='newtextq'><button type='button' onclick='ts2ajaxsubmit()' class='btn'> Submit </button>")
    
def jq_example2_submit(request):
    if request.GET:
        newtext = request.GET['newtext']
        return HttpResponse("<span id='ts2''>" + newtext + "</span>" +
                            "<button id ='ts2-swap-btn' swap-area-id='test-area2'" +
                            " class='btn' type='button' onclick='ts2ajaxedit()'>Swap Text</button>")
    else:
        return HttpResponse("<p>'newtext' not defined")
        
    